//! ION-DTN configuration file generation.
//!
//! Generates the four ION admin script files (.ionrc, .bprc, .ltprc, .ipnrc)
//! from a canonical `NetworkConfiguration`. Respects amateur radio compliance
//! by never emitting BPSec directives and honoring callsign EIDs.

use std::collections::HashMap;
use std::fmt::Write;

use crate::adapter::traits::GeneratedConfig;
use crate::model::config::NetworkConfiguration;
use crate::model::contact_plan::ContactPlan;
use crate::model::neighbor::{ConvergenceLayerLink, Neighbor};
use crate::model::node::{EndpointId, NodeDefinition};
use crate::model::routing::{RoutingConfig, RoutingStrategy};

/// Default LTP max sessions window for ltpadmin initialization.
const DEFAULT_LTP_MAX_SESSIONS: u32 = 32;

/// Default LTP span parameters.
const DEFAULT_MAX_EXPORT_SESSIONS: u32 = 32;
const DEFAULT_MAX_IMPORT_SESSIONS: u32 = 32;
const DEFAULT_MAX_SEGMENT_SIZE: u32 = 1400;
const DEFAULT_BLOCK_SIZE: u32 = 100000;
const DEFAULT_AGGREGATION_TIME_LIMIT: u32 = 1;

/// Default ION production/consumption rates (bytes per second).
const DEFAULT_PRODUCTION_RATE: u64 = 1000000;
const DEFAULT_CONSUMPTION_RATE: u64 = 1000000;

/// Default LTP protocol payload size and overhead for bpadmin.
const DEFAULT_LTP_PAYLOAD_SIZE: u32 = 1400;
const DEFAULT_LTP_OVERHEAD: u32 = 100;

/// Generate all ION configuration files from a canonical network configuration.
///
/// Returns a `GeneratedConfig` containing:
/// - `node<N>.ionrc` — ionadmin initialization and contact/range commands
/// - `node<N>.bprc` — bpadmin endpoint, protocol, induct/outduct commands
/// - `node<N>.ltprc` — ltpadmin span commands for LTP neighbors
/// - `node<N>.ipnrc` — ipnadmin routing plan commands
pub fn generate_ion_config(config: &NetworkConfiguration) -> GeneratedConfig {
    let node_num = config.local_node.node_number;
    let prefix = format!("node{}", node_num);

    let mut files = HashMap::new();

    files.insert(
        format!("{}.ionrc", prefix),
        generate_ionrc(config),
    );
    files.insert(
        format!("{}.bprc", prefix),
        generate_bprc(config),
    );
    files.insert(
        format!("{}.ltprc", prefix),
        generate_ltprc(config),
    );
    files.insert(
        format!("{}.ipnrc", prefix),
        generate_ipnrc(config),
    );

    GeneratedConfig { files }
}

/// Generate the .ionrc file (ionadmin commands).
///
/// Contains:
/// - Initialization command (`1 <node_number> ''`)
/// - Start command (`s`)
/// - Contact commands from the contact plan
/// - Range commands from the contact plan
/// - Production/consumption rate commands
fn generate_ionrc(config: &NetworkConfiguration) -> String {
    let mut out = String::new();

    // ION initialization: 1 <node_number> ''
    writeln!(out, "## File: ionadmin configuration for node {}", config.local_node.node_number).unwrap();
    writeln!(out, "## Generated by radiant-dtn-abstraction (ION adapter)").unwrap();
    writeln!(out, "## Amateur radio compliant: no BPSec directives").unwrap();
    writeln!(out).unwrap();

    // Initialize the node
    writeln!(out, "1 {} ''", config.local_node.node_number).unwrap();
    writeln!(out).unwrap();

    // Start ION
    writeln!(out, "s").unwrap();
    writeln!(out).unwrap();

    // Contact commands
    write_contact_commands(&mut out, &config.contact_plan, config.local_node.node_number);

    // Range commands
    write_range_commands(&mut out, &config.contact_plan, config.local_node.node_number);

    // Production and consumption rate management
    writeln!(out, "## Production/consumption rates").unwrap();
    writeln!(out, "m production {}", DEFAULT_PRODUCTION_RATE).unwrap();
    writeln!(out, "m consumption {}", DEFAULT_CONSUMPTION_RATE).unwrap();
    writeln!(out).unwrap();

    out
}

/// Write contact plan contact commands to ionrc output.
///
/// Injects a self-contact (loopback) entry before the user-defined contacts.
/// ION's CGR requires this to know the local node can process bundles internally.
fn write_contact_commands(out: &mut String, contact_plan: &ContactPlan, local_node_number: u64) {
    writeln!(out, "## Contacts").unwrap();
    // Self-contact: ION requires a loopback contact for internal bundle processing
    writeln!(
        out,
        "a contact +0 +86400 {} {} 100000",
        local_node_number, local_node_number
    ).unwrap();
    for contact in &contact_plan.contacts {
        writeln!(
            out,
            "a contact +{} +{} {} {} {}",
            contact.start_time,
            contact.end_time,
            contact.source_node,
            contact.dest_node,
            contact.rate_bps
        ).unwrap();
    }
    writeln!(out).unwrap();
}

/// Write contact plan range commands to ionrc output.
///
/// Injects a self-range (zero OWLT loopback) entry before the user-defined ranges.
/// ION requires this for CGR to compute routes through the local node.
fn write_range_commands(out: &mut String, contact_plan: &ContactPlan, local_node_number: u64) {
    writeln!(out, "## Ranges").unwrap();
    // Self-range: zero OWLT to self (required by ION for internal routing)
    writeln!(
        out,
        "a range +0 +9999999999 {} {} 0",
        local_node_number, local_node_number
    ).unwrap();
    for range in &contact_plan.ranges {
        // ION uses integer OWLT in seconds; round up to at least 1 second
        // for non-zero OWLT values (ION's CGR needs OWLT >= 1 for real links)
        let owlt = if range.owlt_secs > 0.0 {
            (range.owlt_secs.ceil() as i64).max(1)
        } else {
            0
        };
        writeln!(
            out,
            "a range +0 +9999999999 {} {} {}",
            range.source_node,
            range.dest_node,
            owlt
        ).unwrap();
    }
    writeln!(out).unwrap();
}

/// Generate the .bprc file (bpadmin commands).
///
/// Contains:
/// - Initialization (`1`)
/// - Scheme registration (`a scheme ipn 'ipnfw' 'ipnadminep'`)
/// - Endpoint registrations for the local node
/// - Protocol declarations (ltp, tcp, udp as needed)
/// - Induct/outduct entries per neighbor link
/// - Callsign EID registration if configured
/// - Start command (`s`)
///
/// NOTE: No BPSec directives are generated (amateur radio compliance).
fn generate_bprc(config: &NetworkConfiguration) -> String {
    let mut out = String::new();
    let node_num = config.local_node.node_number;

    writeln!(out, "## File: bpadmin configuration for node {}", node_num).unwrap();
    writeln!(out, "## Generated by radiant-dtn-abstraction (ION adapter)").unwrap();
    writeln!(out, "## Amateur radio compliant: no BPSec directives").unwrap();
    writeln!(out).unwrap();

    // Initialize
    writeln!(out, "1").unwrap();
    writeln!(out).unwrap();

    // Add the IPN scheme
    writeln!(out, "a scheme ipn 'ipnfw' 'ipnadminep'").unwrap();
    writeln!(out).unwrap();

    // Register endpoints for local node services
    writeln!(out, "## Endpoints").unwrap();
    // Default admin endpoint
    writeln!(out, "a endpoint ipn:{}.0 x", node_num).unwrap();
    for svc in &config.local_node.services {
        writeln!(out, "a endpoint ipn:{}.{} x", node_num, svc.service_number).unwrap();
    }

    // Callsign EID registration (amateur radio compliance)
    if let Some(ref callsign_eid) = config.local_node.callsign_eid {
        writeln!(out).unwrap();
        writeln!(out, "## Callsign EID (amateur radio station identification)").unwrap();
        match callsign_eid {
            EndpointId::Dtn { authority, path } => {
                writeln!(out, "a endpoint dtn://{}/{} x", authority, path).unwrap();
            }
            EndpointId::Ipn { node_number, service_number } => {
                writeln!(out, "a endpoint ipn:{}.{} x", node_number, service_number).unwrap();
            }
        }
    }
    writeln!(out).unwrap();

    // Determine which protocols are needed based on neighbor links
    let protocols = collect_protocols(&config.neighbors);
    writeln!(out, "## Protocols").unwrap();
    for proto in &protocols {
        match *proto {
            "ltp" => writeln!(out, "a protocol ltp {} {}", DEFAULT_LTP_PAYLOAD_SIZE, DEFAULT_LTP_OVERHEAD).unwrap(),
            other => writeln!(out, "a protocol {}", other).unwrap(),
        }
    }
    writeln!(out).unwrap();

    // Generate induct/outduct entries per neighbor
    writeln!(out, "## Inducts and Outducts").unwrap();
    for neighbor in &config.neighbors {
        for link in &neighbor.links {
            write_bprc_link_entries(&mut out, &config.local_node, link);
        }
    }
    writeln!(out).unwrap();

    // Start
    writeln!(out, "s").unwrap();

    out
}

/// Collect unique protocol names needed based on neighbor links.
fn collect_protocols(neighbors: &[Neighbor]) -> Vec<&'static str> {
    let mut has_ltp = false;
    let mut has_tcp = false;
    let mut has_udp = false;

    for neighbor in neighbors {
        for link in &neighbor.links {
            match link {
                ConvergenceLayerLink::LtpUdp { .. } => has_ltp = true,
                ConvergenceLayerLink::Kiss { .. } => has_ltp = true, // KISS uses LTP framing
                ConvergenceLayerLink::TcpCl { .. } => has_tcp = true,
                ConvergenceLayerLink::Udp { .. } => has_udp = true,
            }
        }
    }

    let mut protocols = Vec::new();
    if has_ltp {
        protocols.push("ltp");
    }
    if has_tcp {
        protocols.push("tcp");
    }
    if has_udp {
        protocols.push("udp");
    }
    protocols
}

/// Write induct/outduct entries for a single convergence layer link.
fn write_bprc_link_entries(out: &mut String, _local_node: &NodeDefinition, link: &ConvergenceLayerLink) {
    match link {
        ConvergenceLayerLink::LtpUdp {
            local_engine_id,
            remote_engine_id,
            ..
        } => {
            writeln!(out, "a induct ltp {} ltpcli", local_engine_id).unwrap();
            writeln!(out, "a outduct ltp {} ltpclo", remote_engine_id).unwrap();
        }
        ConvergenceLayerLink::Kiss {
            local_engine_id,
            remote_engine_id,
            ..
        } => {
            // KISS CLA uses LTP framing — same induct/outduct syntax as LTP/UDP
            writeln!(out, "a induct ltp {} ltpcli", local_engine_id).unwrap();
            writeln!(out, "a outduct ltp {} ltpclo", remote_engine_id).unwrap();
        }
        ConvergenceLayerLink::TcpCl {
            remote_host,
            remote_port,
            local_port,
            ..
        } => {
            let lport = local_port.unwrap_or(4556);
            writeln!(out, "a induct tcp {}:{} tcpcli", remote_host, lport).unwrap();
            writeln!(
                out,
                "a outduct tcp {}:{} tcpclo",
                remote_host, remote_port
            ).unwrap();
        }
        ConvergenceLayerLink::Udp {
            remote_host,
            remote_port,
            local_port,
            ..
        } => {
            let lport = local_port.unwrap_or(4556);
            writeln!(out, "a induct udp {}:{} udpcli", remote_host, lport).unwrap();
            writeln!(
                out,
                "a outduct udp {}:{} udpclo",
                remote_host, remote_port
            ).unwrap();
        }
    }
}

/// Generate the .ltprc file (ltpadmin commands).
///
/// Contains:
/// - Initialization (`1 32`) — 32 is the max sessions window
/// - Span entries for each LTP neighbor (LTP/UDP and KISS links)
/// - Start command (`s 'udplsi <local_bind_addr>:<local_port>'`)
fn generate_ltprc(config: &NetworkConfiguration) -> String {
    let mut out = String::new();
    let node_num = config.local_node.node_number;

    writeln!(out, "## File: ltpadmin configuration for node {}", node_num).unwrap();
    writeln!(out, "## Generated by radiant-dtn-abstraction (ION adapter)").unwrap();
    writeln!(out).unwrap();

    // Initialize LTP: 1 <max_sessions_window>
    writeln!(out, "1 {}", DEFAULT_LTP_MAX_SESSIONS).unwrap();
    writeln!(out).unwrap();

    // Add spans for each LTP neighbor
    writeln!(out, "## LTP Spans").unwrap();

    // Loopback span: ION requires an LTP span to itself for internal bundle processing
    let local_port = find_local_ltp_port(config);
    writeln!(
        out,
        "a span {} {} {} {} {} {} 'udplso 127.0.0.1:{}'",
        node_num,
        DEFAULT_MAX_EXPORT_SESSIONS,
        DEFAULT_MAX_IMPORT_SESSIONS,
        DEFAULT_MAX_SEGMENT_SIZE,
        DEFAULT_BLOCK_SIZE,
        DEFAULT_AGGREGATION_TIME_LIMIT,
        local_port,
    ).unwrap();

    for neighbor in &config.neighbors {
        for link in &neighbor.links {
            write_ltprc_span(&mut out, link);
        }
    }
    writeln!(out).unwrap();

    // Start LTP listener (LSI) — bind on 0.0.0.0 with the local port
    let local_port = find_local_ltp_port(config);
    writeln!(out, "s 'udplsi 0.0.0.0:{}'", local_port).unwrap();

    out
}

/// Find the local LTP port from the configuration.
/// Uses the first LTP/UDP link's local_port, or falls back to 1113.
fn find_local_ltp_port(config: &NetworkConfiguration) -> u16 {
    for neighbor in &config.neighbors {
        for link in &neighbor.links {
            if let ConvergenceLayerLink::LtpUdp { local_port, .. } = link {
                return *local_port;
            }
        }
    }
    1113
}

/// Write an LTP span entry for an LTP-based link (LTP/UDP or KISS).
///
/// Format: `a span <remote_engine_id> <max_export> <max_import> <seg_size> <block_size> <agg_time> '<lso_command>'`
fn write_ltprc_span(out: &mut String, link: &ConvergenceLayerLink) {
    match link {
        ConvergenceLayerLink::LtpUdp {
            remote_engine_id,
            remote_host,
            remote_port,
            mtu,
            ..
        } => {
            let seg_size = mtu.unwrap_or(DEFAULT_MAX_SEGMENT_SIZE);
            writeln!(
                out,
                "a span {} {} {} {} {} {} 'udplso {}:{}'",
                remote_engine_id,
                DEFAULT_MAX_EXPORT_SESSIONS,
                DEFAULT_MAX_IMPORT_SESSIONS,
                seg_size,
                DEFAULT_BLOCK_SIZE,
                DEFAULT_AGGREGATION_TIME_LIMIT,
                remote_host,
                remote_port,
            ).unwrap();
        }
        ConvergenceLayerLink::Kiss {
            remote_engine_id,
            frame_size,
            tnc_device,
            ..
        } => {
            // KISS CLA uses LTP framing; the span references the KISS link
            // service adapter commands instead of UDP LSO
            let seg_size = frame_size.unwrap_or(DEFAULT_MAX_SEGMENT_SIZE);
            writeln!(
                out,
                "a span {} {} {} {} {} {} 'kisslo {}'",
                remote_engine_id,
                DEFAULT_MAX_EXPORT_SESSIONS,
                DEFAULT_MAX_IMPORT_SESSIONS,
                seg_size,
                DEFAULT_BLOCK_SIZE,
                DEFAULT_AGGREGATION_TIME_LIMIT,
                tnc_device,
            ).unwrap();
        }
        // TCP and UDP links don't use LTP spans
        _ => {}
    }
}

/// Generate the .ipnrc file (ipnadmin commands).
///
/// Contains:
/// - Plan entries mapping each neighbor to its LTP engine ID (for LTP)
///   or TCP/UDP address (for TCP/UDP links)
/// - Routing strategy configuration
fn generate_ipnrc(config: &NetworkConfiguration) -> String {
    let mut out = String::new();
    let node_num = config.local_node.node_number;

    writeln!(out, "## File: ipnadmin configuration for node {}", node_num).unwrap();
    writeln!(out, "## Generated by radiant-dtn-abstraction (ION adapter)").unwrap();
    writeln!(out).unwrap();

    // Generate routing configuration
    write_routing_config(&mut out, &config.routing);

    // Generate plan entries for each neighbor
    writeln!(out, "## Forwarding plans").unwrap();
    for neighbor in &config.neighbors {
        write_ipnrc_plan(&mut out, neighbor);
    }

    out
}

/// Write routing strategy configuration to ipnrc.
fn write_routing_config(out: &mut String, routing: &RoutingConfig) {
    match routing.strategy {
        RoutingStrategy::Cgr => {
            // CGR is the default for ION when contact plan data is present
            writeln!(out, "## Routing: Contact Graph Routing (CGR)").unwrap();
        }
        RoutingStrategy::Static => {
            writeln!(out, "## Routing: Static routes").unwrap();
            for route in &routing.static_routes {
                writeln!(
                    out,
                    "a plan {} ltp/{}",
                    route.destination_node, route.next_hop_node
                ).unwrap();
            }
        }
        RoutingStrategy::Default => {
            writeln!(out, "## Routing: Backend default").unwrap();
        }
    }
    writeln!(out).unwrap();
}

/// Write a forwarding plan entry for a neighbor.
///
/// For LTP-based links (LTP/UDP or KISS), the plan uses `ltp/<engine_id>`.
/// For TCP links, the plan uses `tcp/<host>:<port>`.
/// For UDP links, the plan uses `udp/<host>:<port>`.
fn write_ipnrc_plan(out: &mut String, neighbor: &Neighbor) {
    // Use the first link to determine the duct expression for the plan
    if let Some(link) = neighbor.links.first() {
        let duct_expr = link_to_duct_expression(link);
        writeln!(out, "a plan {} {}", neighbor.node_number, duct_expr).unwrap();
    }
}

/// Map a convergence layer link to an ION duct expression for ipnadmin plans.
fn link_to_duct_expression(link: &ConvergenceLayerLink) -> String {
    match link {
        ConvergenceLayerLink::LtpUdp { remote_engine_id, .. } => {
            format!("ltp/{}", remote_engine_id)
        }
        ConvergenceLayerLink::Kiss { remote_engine_id, .. } => {
            // KISS uses LTP framing, so the duct expression is the same as LTP
            format!("ltp/{}", remote_engine_id)
        }
        ConvergenceLayerLink::TcpCl { remote_host, remote_port, .. } => {
            format!("tcp/{}:{}", remote_host, remote_port)
        }
        ConvergenceLayerLink::Udp { remote_host, remote_port, .. } => {
            format!("udp/{}:{}", remote_host, remote_port)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::config::{NetworkConfiguration, SecurityConfig, StorageConfig};
    use crate::model::contact_plan::{Contact, ContactPlan, Range};
    use crate::model::neighbor::{ConvergenceLayerLink, Neighbor};
    use crate::model::node::{EndpointId, NodeDefinition, ServiceDemux};
    use crate::model::routing::{RoutingConfig, RoutingStrategy};

    fn sample_config() -> NetworkConfiguration {
        NetworkConfiguration {
            version: "1.0".to_string(),
            backend: "ion-dtn".to_string(),
            local_node: NodeDefinition {
                node_number: 10,
                endpoint_id: Some(EndpointId::Ipn {
                    node_number: 10,
                    service_number: 0,
                }),
                callsign_eid: Some(EndpointId::Dtn {
                    authority: "g4dpz-1".to_string(),
                    path: "gs".to_string(),
                }),
                name: "G4DPZ Ground Station".to_string(),
                services: vec![
                    ServiceDemux { service_number: 1, description: Some("Bundle delivery".to_string()) },
                    ServiceDemux { service_number: 2047, description: Some("Echo".to_string()) },
                ],
            },
            neighbors: vec![
                Neighbor {
                    node_number: 20,
                    name: Some("Lunar Orbiter".to_string()),
                    links: vec![
                        ConvergenceLayerLink::LtpUdp {
                            id: "ltp-to-orbiter".to_string(),
                            local_engine_id: 10,
                            remote_engine_id: 20,
                            remote_host: "192.168.1.20".to_string(),
                            remote_port: 1113,
                            local_port: 2113,
                            mtu: Some(1360),
                            segment_rate: None,
                        },
                    ],
                    rate_limit_bps: None,
                },
            ],
            contact_plan: ContactPlan {
                contacts: vec![
                    Contact {
                        source_node: 10,
                        dest_node: 20,
                        start_time: 1700000000,
                        end_time: 1700003600,
                        rate_bps: 9600,
                        confidence: 0.95,
                    },
                ],
                ranges: vec![
                    Range {
                        source_node: 10,
                        dest_node: 20,
                        owlt_secs: 1.3,
                    },
                ],
            },
            routing: RoutingConfig {
                strategy: RoutingStrategy::Cgr,
                static_routes: vec![],
            },
            security: Some(SecurityConfig { enabled: false }),
            storage: Some(StorageConfig {
                path: "/var/radiant/bundles".to_string(),
                max_bytes: Some(1073741824),
            }),
            backend_options: std::collections::HashMap::new(),
        }
    }

    #[test]
    fn test_ionrc_contains_initialization() {
        let config = sample_config();
        let ionrc = generate_ionrc(&config);
        assert!(ionrc.contains("1 10 ''"));
        assert!(ionrc.contains("\ns\n"));
    }

    #[test]
    fn test_ionrc_contains_contacts() {
        let config = sample_config();
        let ionrc = generate_ionrc(&config);
        assert!(ionrc.contains("a contact +1700000000 +1700003600 10 20 9600"));
    }

    #[test]
    fn test_ionrc_contains_ranges() {
        let config = sample_config();
        let ionrc = generate_ionrc(&config);
        // OWLT 1.3 rounds up to 2 (ION uses integer seconds, ceil for safety)
        assert!(ionrc.contains("a range +0 +9999999999 10 20 2"));
    }

    #[test]
    fn test_ionrc_contains_production_consumption() {
        let config = sample_config();
        let ionrc = generate_ionrc(&config);
        assert!(ionrc.contains("m production 1000000"));
        assert!(ionrc.contains("m consumption 1000000"));
    }

    #[test]
    fn test_bprc_contains_endpoints() {
        let config = sample_config();
        let bprc = generate_bprc(&config);
        assert!(bprc.contains("a endpoint ipn:10.0 x"));
        assert!(bprc.contains("a endpoint ipn:10.1 x"));
        assert!(bprc.contains("a endpoint ipn:10.2047 x"));
    }

    #[test]
    fn test_bprc_contains_callsign_eid() {
        let config = sample_config();
        let bprc = generate_bprc(&config);
        assert!(bprc.contains("a endpoint dtn://g4dpz-1/gs x"));
    }

    #[test]
    fn test_bprc_contains_ltp_protocol() {
        let config = sample_config();
        let bprc = generate_bprc(&config);
        assert!(bprc.contains("a protocol ltp 1400 100"));
    }

    #[test]
    fn test_bprc_contains_induct_outduct() {
        let config = sample_config();
        let bprc = generate_bprc(&config);
        assert!(bprc.contains("a induct ltp 10 ltpcli"));
        assert!(bprc.contains("a outduct ltp 20 ltpclo"));
    }

    #[test]
    fn test_bprc_no_bpsec_directives() {
        let config = sample_config();
        let bprc = generate_bprc(&config);
        // Ensure no BPSec security command directives are present
        // (comments mentioning compliance are fine; actual commands are not)
        assert!(!bprc.contains("a bpsource"));
        assert!(!bprc.contains("a bibrule"));
        assert!(!bprc.contains("a bcbrule"));
        assert!(!bprc.contains("a bib"));
        assert!(!bprc.contains("a bcb"));
        // No key management or encryption commands
        let lines: Vec<&str> = bprc.lines()
            .filter(|l| !l.starts_with("##"))
            .collect();
        let non_comment = lines.join("\n").to_lowercase();
        assert!(!non_comment.contains("encrypt"));
        assert!(!non_comment.contains("hmac"));
    }

    #[test]
    fn test_ltprc_contains_initialization() {
        let config = sample_config();
        let ltprc = generate_ltprc(&config);
        // Should initialize with just the max sessions window
        assert!(ltprc.contains("1 32"));
    }

    #[test]
    fn test_ltprc_contains_span() {
        let config = sample_config();
        let ltprc = generate_ltprc(&config);
        // Should have a span for remote engine 20 with udplso command
        assert!(ltprc.contains("a span 20"));
        assert!(ltprc.contains("'udplso 192.168.1.20:1113'"));
    }

    #[test]
    fn test_ltprc_contains_start() {
        let config = sample_config();
        let ltprc = generate_ltprc(&config);
        assert!(ltprc.contains("s 'udplsi 0.0.0.0:2113'"));
    }

    #[test]
    fn test_ipnrc_contains_plan() {
        let config = sample_config();
        let ipnrc = generate_ipnrc(&config);
        assert!(ipnrc.contains("a plan 20 ltp/20"));
    }

    #[test]
    fn test_generate_ion_config_produces_all_files() {
        let config = sample_config();
        let generated = generate_ion_config(&config);
        assert!(generated.files.contains_key("node10.ionrc"));
        assert!(generated.files.contains_key("node10.bprc"));
        assert!(generated.files.contains_key("node10.ltprc"));
        assert!(generated.files.contains_key("node10.ipnrc"));
    }

    #[test]
    fn test_kiss_link_generates_ltp_entries() {
        let mut config = sample_config();
        config.neighbors = vec![Neighbor {
            node_number: 30,
            name: Some("KISS TNC Peer".to_string()),
            links: vec![ConvergenceLayerLink::Kiss {
                id: "kiss-tnc".to_string(),
                tnc_device: "/dev/ttyUSB0".to_string(),
                baud_rate: 9600,
                local_engine_id: 10,
                remote_engine_id: 30,
                frame_size: Some(256),
            }],
            rate_limit_bps: None,
        }];

        let bprc = generate_bprc(&config);
        assert!(bprc.contains("a protocol ltp 1400 100"));
        assert!(bprc.contains("a induct ltp 10 ltpcli"));
        assert!(bprc.contains("a outduct ltp 30 ltpclo"));

        let ltprc = generate_ltprc(&config);
        assert!(ltprc.contains("a span 30"));
        assert!(ltprc.contains("'kisslo /dev/ttyUSB0'"));

        let ipnrc = generate_ipnrc(&config);
        assert!(ipnrc.contains("a plan 30 ltp/30"));
    }

    #[test]
    fn test_cgr_routing_no_explicit_plans_from_static() {
        let config = sample_config();
        let ipnrc = generate_ipnrc(&config);
        assert!(ipnrc.contains("Contact Graph Routing"));
    }

    #[test]
    fn test_static_routing_generates_plans() {
        let mut config = sample_config();
        config.routing = RoutingConfig {
            strategy: RoutingStrategy::Static,
            static_routes: vec![
                crate::model::routing::StaticRoute {
                    destination_node: 20,
                    next_hop_node: 15,
                },
            ],
        };

        let ipnrc = generate_ipnrc(&config);
        assert!(ipnrc.contains("Static routes"));
        assert!(ipnrc.contains("a plan 20 ltp/15"));
    }

    #[test]
    fn test_tcp_link_generates_tcp_entries() {
        let mut config = sample_config();
        config.neighbors = vec![Neighbor {
            node_number: 40,
            name: Some("TCP Peer".to_string()),
            links: vec![ConvergenceLayerLink::TcpCl {
                id: "tcp-link".to_string(),
                remote_host: "10.0.0.40".to_string(),
                remote_port: 4556,
                local_port: Some(4557),
                keepalive_interval_secs: Some(30),
            }],
            rate_limit_bps: None,
        }];

        let bprc = generate_bprc(&config);
        assert!(bprc.contains("a protocol tcp"));
        assert!(bprc.contains("a induct tcp 10.0.0.40:4557 tcpcli"));
        assert!(bprc.contains("a outduct tcp 10.0.0.40:4556 tcpclo"));

        let ipnrc = generate_ipnrc(&config);
        assert!(ipnrc.contains("a plan 40 tcp/10.0.0.40:4556"));
    }

    #[test]
    fn test_ionrc_contains_self_contact() {
        let config = sample_config();
        let ionrc = generate_ionrc(&config);
        // Self-contact must be present with local node number (10) as both src and dest
        assert!(ionrc.contains("a contact +0 +86400 10 10 100000"));
    }

    #[test]
    fn test_ionrc_self_contact_appears_before_user_contacts() {
        let config = sample_config();
        let ionrc = generate_ionrc(&config);
        let self_pos = ionrc.find("a contact +0 +86400 10 10 100000").unwrap();
        let user_pos = ionrc.find("a contact +1700000000 +1700003600 10 20 9600").unwrap();
        assert!(self_pos < user_pos, "Self-contact must appear before user contacts");
    }

    #[test]
    fn test_ionrc_contains_self_range() {
        let config = sample_config();
        let ionrc = generate_ionrc(&config);
        // Self-range must be present with local node number (10) and zero OWLT
        assert!(ionrc.contains("a range +0 +9999999999 10 10 0"));
    }

    #[test]
    fn test_ionrc_self_range_appears_before_user_ranges() {
        let config = sample_config();
        let ionrc = generate_ionrc(&config);
        let self_pos = ionrc.find("a range +0 +9999999999 10 10 0").unwrap();
        let user_pos = ionrc.find("a range +0 +9999999999 10 20 2").unwrap();
        assert!(self_pos < user_pos, "Self-range must appear before user ranges");
    }

    #[test]
    fn test_ltprc_contains_loopback_span() {
        let config = sample_config();
        let ltprc = generate_ltprc(&config);
        // Loopback span for local engine 10, targeting 127.0.0.1:2113
        assert!(ltprc.contains("a span 10 32 32 1400 100000 1 'udplso 127.0.0.1:2113'"));
    }

    #[test]
    fn test_ltprc_loopback_span_appears_before_neighbor_spans() {
        let config = sample_config();
        let ltprc = generate_ltprc(&config);
        let loopback_pos = ltprc.find("a span 10").unwrap();
        let neighbor_pos = ltprc.find("a span 20").unwrap();
        assert!(loopback_pos < neighbor_pos, "Loopback span must appear before neighbor spans");
    }

    #[test]
    fn test_ionrc_self_entries_present_with_empty_contact_plan() {
        let mut config = sample_config();
        config.contact_plan = ContactPlan {
            contacts: vec![],
            ranges: vec![],
        };
        let ionrc = generate_ionrc(&config);
        // Self-contact and self-range must still be generated even with no user contacts/ranges
        assert!(ionrc.contains("a contact +0 +86400 10 10 100000"));
        assert!(ionrc.contains("a range +0 +9999999999 10 10 0"));
    }
}
