//! Hardy BPA server configuration generation.
//!
//! Generates Hardy's real `config.yaml` format from a canonical `NetworkConfiguration`.
//! Hardy uses a YAML config with: node-ids, grpc, storage, rfc9171-validity,
//! built-in-services, static-routes, and clas sections.
//!
//! Key behaviors:
//! - `node-ids` includes BOTH `ipn:` and `dtn://` scheme identifiers (Hardy requires both)
//! - `rfc9171-validity` disables primary-block-integrity for amateur radio (no BPSec)
//! - TCPCL neighbors produce `clas` entries with type `tcpclv4`
//! - LTP/UDP/KISS neighbors are noted as requiring separate `hardy-ltp-cla` binary
//! - Contact plan data is NOT in config.yaml (managed via gRPC runtime API)
//! - Static routes produce a separate `static_routes.yaml` file

use std::collections::HashMap;
use std::fmt::Write;

use crate::adapter::traits::GeneratedConfig;
use crate::model::config::NetworkConfiguration;
use crate::model::neighbor::{ConvergenceLayerLink, Neighbor};
use crate::model::node::{EndpointId, NodeDefinition};
use crate::model::routing::{RoutingConfig, RoutingStrategy};

/// Generate the Hardy BPA server configuration from a canonical network configuration.
///
/// Returns a `GeneratedConfig` containing:
/// - `hardy.yaml` — the main Hardy BPA server config
/// - `static_routes.yaml` — (only if routing strategy is Static) the routes file
/// - `ltp-cla.yaml` — (only if LTP/UDP links exist) the hardy-ltp-cla config
///
/// Notes on what is NOT in the config:
/// - Contact plan data: Hardy manages contacts via gRPC runtime API
pub fn generate_hardy_config(config: &NetworkConfiguration) -> GeneratedConfig {
    let mut files = HashMap::new();

    let yaml_content = generate_hardy_yaml(config);
    files.insert("hardy.yaml".to_string(), yaml_content);

    // Generate static_routes.yaml if routing strategy is Static
    if config.routing.strategy == RoutingStrategy::Static
        && !config.routing.static_routes.is_empty()
    {
        let routes_content = generate_static_routes_yaml(config);
        files.insert("static_routes.yaml".to_string(), routes_content);
    }

    // Generate ltp-cla.yaml if any LTP/UDP links are configured
    if let Some(ltp_cla_content) = generate_ltp_cla_yaml(config) {
        files.insert("ltp-cla.yaml".to_string(), ltp_cla_content);
    }

    GeneratedConfig { files }
}

/// Generate the hardy-ltp-cla configuration YAML from the canonical config.
///
/// Produces the config expected by the `hardy-ltp-server` binary:
///
/// ```yaml
/// grpc:
///   endpoint: "http://127.0.0.1:50051"
///   reconnect-initial-secs: 1.0
///   reconnect-max-secs: 10.0
///
/// ltp:
///   bind: "0.0.0.0:<local_port>"
///   engine-id: <local_engine_id>
///   client-service-id: 1
///   spans:
///     - engine-id: <remote_engine_id>
///       address: "<remote_host>:<remote_port>"
///       max-segment-size: <mtu>
///       framing: none
///       node-ids:
///         - "ipn:<remote_node>.0"
/// ```
///
/// Returns `None` if no LTP/UDP links are configured.
pub fn generate_ltp_cla_yaml(config: &NetworkConfiguration) -> Option<String> {
    // Collect all LTP/UDP links from neighbors
    let ltp_links: Vec<(&Neighbor, &ConvergenceLayerLink)> = config
        .neighbors
        .iter()
        .flat_map(|n| n.links.iter().map(move |l| (n, l)))
        .filter(|(_, l)| matches!(l, ConvergenceLayerLink::LtpUdp { .. }))
        .collect();

    if ltp_links.is_empty() {
        return None;
    }

    // Determine local engine ID and local bind port from the first LTP link.
    // All LTP links on the same node share the same local engine ID and bind port.
    let (local_engine_id, local_port) = match &ltp_links[0].1 {
        ConvergenceLayerLink::LtpUdp {
            local_engine_id,
            local_port,
            ..
        } => (*local_engine_id, *local_port),
        _ => unreachable!(),
    };

    // Determine the gRPC endpoint for connecting to the Hardy BPA.
    let grpc_address = config
        .backend_options
        .get("grpc_address")
        .and_then(|v| v.as_str())
        .unwrap_or("[::1]:50051");

    let mut out = String::new();

    writeln!(out, "# hardy-ltp-cla (hardy-ltp-server) configuration").unwrap();
    writeln!(out, "# Generated by radiant-dtn-abstraction (Hardy adapter)").unwrap();
    writeln!(
        out,
        "# Bridges Hardy BPA (gRPC) <-> LTP/UDP for interoperability"
    )
    .unwrap();
    writeln!(out).unwrap();

    // gRPC section
    writeln!(out, "grpc:").unwrap();
    writeln!(out, "  endpoint: \"http://{}\"", grpc_address).unwrap();
    writeln!(out, "  reconnect-initial-secs: 1.0").unwrap();
    writeln!(out, "  reconnect-max-secs: 10.0").unwrap();
    writeln!(out).unwrap();

    // LTP section
    writeln!(out, "ltp:").unwrap();
    writeln!(out, "  bind: \"0.0.0.0:{}\"", local_port).unwrap();
    writeln!(out, "  engine-id: {}", local_engine_id).unwrap();
    writeln!(out, "  client-service-id: 1").unwrap();
    writeln!(out, "  spans:").unwrap();

    for (neighbor, link) in &ltp_links {
        if let ConvergenceLayerLink::LtpUdp {
            remote_engine_id,
            remote_host,
            remote_port,
            mtu,
            ..
        } = link
        {
            let max_segment_size = mtu.unwrap_or(1400);
            writeln!(out, "    - engine-id: {}", remote_engine_id).unwrap();
            writeln!(out, "      address: \"{}:{}\"", remote_host, remote_port).unwrap();
            writeln!(out, "      max-segment-size: {}", max_segment_size).unwrap();
            writeln!(out, "      framing: none").unwrap();
            writeln!(out, "      node-ids:").unwrap();
            writeln!(out, "        - \"ipn:{}.0\"", neighbor.node_number).unwrap();
        }
    }

    Some(out)
}

/// Generate the complete Hardy BPA server config.yaml content.
fn generate_hardy_yaml(config: &NetworkConfiguration) -> String {
    let mut out = String::new();

    writeln!(out, "# Hardy BPA server configuration").unwrap();
    writeln!(out, "# Generated by radiant-dtn-abstraction (Hardy adapter)").unwrap();
    writeln!(out, "# Amateur radio compliant: no BPSec/encryption").unwrap();
    writeln!(out).unwrap();

    // log-level
    write_log_level(&mut out, config);

    // node-ids section (MUST include both ipn: and dtn:// schemes)
    write_node_ids_section(&mut out, &config.local_node);

    // grpc section
    write_grpc_section(&mut out, config);

    // storage section
    write_storage_section(&mut out, config);

    // rfc9171-validity section (amateur radio: no BPSec)
    write_rfc9171_validity_section(&mut out);

    // built-in-services section
    write_built_in_services_section(&mut out, &config.local_node);

    // static-routes section (if applicable)
    write_static_routes_section(&mut out, &config.routing);

    // clas section (TCPCLv4 entries from neighbors)
    write_clas_section(&mut out, &config.neighbors);

    out
}

/// Write log-level. Default to "info".
fn write_log_level(out: &mut String, config: &NetworkConfiguration) {
    let level = config
        .backend_options
        .get("log_level")
        .and_then(|v| v.as_str())
        .unwrap_or("info");
    writeln!(out, "log-level: {}", level).unwrap();
    writeln!(out).unwrap();
}

/// Write the `node-ids` section.
///
/// Hardy requires BOTH an `ipn:` and a `dtn://` scheme node ID.
/// - `ipn:<node_number>.0` is always generated from the node number
/// - `dtn://` is taken from callsign_eid if present, otherwise generated
///   as `dtn://node<N>/`
fn write_node_ids_section(out: &mut String, node: &NodeDefinition) {
    writeln!(out, "node-ids:").unwrap();

    // Always emit ipn: scheme ID
    let ipn_id = format!("ipn:{}.0", node.node_number);
    writeln!(out, "  - \"{}\"", ipn_id).unwrap();

    // Emit dtn:// scheme ID
    let dtn_id = match &node.callsign_eid {
        Some(EndpointId::Dtn { authority, path }) => {
            if path.is_empty() {
                format!("dtn://{}/", authority)
            } else {
                format!("dtn://{}/{}", authority, path)
            }
        }
        _ => {
            // Fallback: generate from node number
            format!("dtn://node{}/", node.node_number)
        }
    };
    writeln!(out, "  - \"{}\"", dtn_id).unwrap();
    writeln!(out).unwrap();
}

/// Write the `grpc` section for Hardy management APIs.
fn write_grpc_section(out: &mut String, config: &NetworkConfiguration) {
    let address = config
        .backend_options
        .get("grpc_address")
        .and_then(|v| v.as_str())
        .unwrap_or("[::1]:50051");

    // Determine if LTP service is needed (any LTP/UDP links configured)
    let has_ltp = config.neighbors.iter().any(|n| {
        n.links
            .iter()
            .any(|l| matches!(l, ConvergenceLayerLink::LtpUdp { .. }))
    });

    writeln!(out, "grpc:").unwrap();
    writeln!(out, "  address: \"{}\"", address).unwrap();
    if has_ltp {
        writeln!(out, "  services: [\"application\", \"cla\", \"service\", \"ltp\"]").unwrap();
    } else {
        writeln!(out, "  services: [\"application\", \"cla\", \"service\"]").unwrap();
    }
    writeln!(out).unwrap();
}

/// Write the `storage` section.
///
/// Uses "memory" type by default for testing. If the canonical config
/// specifies a storage path, uses "localdisk" with that path.
fn write_storage_section(out: &mut String, config: &NetworkConfiguration) {
    writeln!(out, "storage:").unwrap();

    match &config.storage {
        Some(storage_cfg) => {
            // Use localdisk for persistent storage
            writeln!(out, "  metadata:").unwrap();
            writeln!(out, "    type: \"sqlite\"").unwrap();
            writeln!(out, "    path: \"{}/metadata.db\"", storage_cfg.path).unwrap();
            writeln!(out, "  bundle:").unwrap();
            writeln!(out, "    type: \"localdisk\"").unwrap();
            writeln!(out, "    path: \"{}/bundles\"", storage_cfg.path).unwrap();
        }
        None => {
            // In-memory for testing
            writeln!(out, "  metadata:").unwrap();
            writeln!(out, "    type: \"memory\"").unwrap();
            writeln!(out, "  bundle:").unwrap();
            writeln!(out, "    type: \"memory\"").unwrap();
        }
    }
    writeln!(out).unwrap();
}

/// Write the `rfc9171-validity` section.
///
/// For amateur radio compliance, BPSec (primary-block-integrity) is disabled.
/// bundle-age-required is also set to false for flexibility.
fn write_rfc9171_validity_section(out: &mut String) {
    writeln!(out, "rfc9171-validity:").unwrap();
    writeln!(out, "  primary-block-integrity: false").unwrap();
    writeln!(out, "  bundle-age-required: false").unwrap();
    writeln!(out).unwrap();
}

/// Write the `built-in-services` section.
///
/// Registers the echo service (service number 7) by default.
/// Additional services from the node definition are included.
/// Deduplicates on both service number and YAML key name.
fn write_built_in_services_section(out: &mut String, node: &NodeDefinition) {
    writeln!(out, "built-in-services:").unwrap();
    // Echo service is always registered
    writeln!(out, "  echo: [7, \"echo\"]").unwrap();

    // Track used key names and service numbers to avoid duplicate YAML keys
    let mut used_keys = std::collections::HashSet::new();
    let mut used_service_numbers = std::collections::HashSet::new();
    used_keys.insert("echo".to_string());
    used_service_numbers.insert(7u64);

    // Add any additional services from the canonical model
    for svc in &node.services {
        // Skip duplicate service numbers (first occurrence wins)
        if used_service_numbers.contains(&svc.service_number) {
            continue;
        }
        used_service_numbers.insert(svc.service_number);

        let desc = svc.description.as_deref().unwrap_or("service");
        let base_name = desc.to_lowercase().replace(' ', "-");

        // Ensure unique key name by appending service number
        let mut key_name = if used_keys.contains(&base_name) {
            format!("{}-{}", base_name, svc.service_number)
        } else {
            base_name.clone()
        };

        // Final safety: if the derived key still collides, append a counter
        let original_key = key_name.clone();
        let mut counter = 2u32;
        while used_keys.contains(&key_name) {
            key_name = format!("{}-{}", original_key, counter);
            counter += 1;
        }
        used_keys.insert(key_name.clone());

        writeln!(out, "  {}: [{}, \"{}\"]", key_name, svc.service_number, desc).unwrap();
    }
    writeln!(out).unwrap();
}

/// Write the `static-routes` section if routing strategy is Static.
///
/// References a separate `static_routes.yaml` file that Hardy will load.
fn write_static_routes_section(out: &mut String, routing: &RoutingConfig) {
    if routing.strategy != RoutingStrategy::Static {
        return;
    }
    writeln!(out, "static-routes:").unwrap();
    writeln!(out, "  routes-file: \"static_routes.yaml\"").unwrap();
    writeln!(out).unwrap();
}

/// Write the `clas` section with CLA entries from neighbors.
///
/// Only TCPCLv4 links are emitted as Hardy CLA entries.
/// LTP/UDP/KISS links require the separate `hardy-ltp-cla` binary
/// and are noted in comments.
fn write_clas_section(out: &mut String, neighbors: &[Neighbor]) {
    let mut tcpcl_entries: Vec<(&Neighbor, &ConvergenceLayerLink)> = Vec::new();
    let mut has_non_tcpcl = false;

    for neighbor in neighbors {
        for link in &neighbor.links {
            match link {
                ConvergenceLayerLink::TcpCl { .. } => {
                    tcpcl_entries.push((neighbor, link));
                }
                _ => {
                    has_non_tcpcl = true;
                }
            }
        }
    }

    if tcpcl_entries.is_empty() && !has_non_tcpcl {
        return;
    }

    if !tcpcl_entries.is_empty() {
        writeln!(out, "clas:").unwrap();
        for (idx, (_neighbor, link)) in tcpcl_entries.iter().enumerate() {
            if let ConvergenceLayerLink::TcpCl {
                id,
                remote_host: _,
                remote_port: _,
                local_port,
                ..
            } = link
            {
                let name = if id.is_empty() {
                    format!("tcp-cla-{}", idx + 1)
                } else {
                    id.clone()
                };
                let listen_port = local_port.unwrap_or(4556);
                writeln!(out, "  - name: \"{}\"", name).unwrap();
                writeln!(out, "    type: \"tcpclv4\"").unwrap();
                writeln!(out, "    address: \"[::]:{}\"", listen_port).unwrap();
                writeln!(out, "    segment-mru: 16384").unwrap();
                writeln!(out, "    transfer-mru: 562949953421312").unwrap();
            }
        }
    }

    // Note non-TCPCL links that need external CLA binaries
    if has_non_tcpcl {
        writeln!(out).unwrap();
        writeln!(
            out,
            "# NOTE: LTP/UDP/KISS convergence layers require the separate"
        )
        .unwrap();
        writeln!(
            out,
            "# hardy-ltp-cla binary. Configure it independently."
        )
        .unwrap();
        for neighbor in neighbors {
            for link in &neighbor.links {
                match link {
                    ConvergenceLayerLink::LtpUdp { id, remote_host, remote_port, .. } => {
                        writeln!(
                            out,
                            "# - LTP/UDP link \"{}\" -> {}:{}",
                            id, remote_host, remote_port
                        )
                        .unwrap();
                    }
                    ConvergenceLayerLink::Kiss { id, tnc_device, .. } => {
                        writeln!(
                            out,
                            "# - KISS link \"{}\" via {}",
                            id, tnc_device
                        )
                        .unwrap();
                    }
                    ConvergenceLayerLink::Udp { id, remote_host, remote_port, .. } => {
                        writeln!(
                            out,
                            "# - UDP link \"{}\" -> {}:{}",
                            id, remote_host, remote_port
                        )
                        .unwrap();
                    }
                    ConvergenceLayerLink::TcpCl { .. } => {}
                }
            }
        }
    }
}

/// Generate the `static_routes.yaml` file content.
///
/// Hardy expects static routes in a separate YAML file referenced
/// by the `static-routes.routes-file` config key.
fn generate_static_routes_yaml(config: &NetworkConfiguration) -> String {
    let mut out = String::new();

    writeln!(out, "# Hardy static routes").unwrap();
    writeln!(out, "# Generated by radiant-dtn-abstraction").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "routes:").unwrap();

    for route in &config.routing.static_routes {
        // Routes map destination EID pattern to next-hop node
        writeln!(
            out,
            "  - destination: \"ipn:{}.0\"",
            route.destination_node
        )
        .unwrap();
        writeln!(out, "    next-hop: \"ipn:{}.0\"", route.next_hop_node).unwrap();
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::config::{NetworkConfiguration, SecurityConfig, StorageConfig};
    use crate::model::contact_plan::{Contact, ContactPlan, Range};
    use crate::model::neighbor::{ConvergenceLayerLink, Neighbor};
    use crate::model::node::{EndpointId, NodeDefinition, ServiceDemux};
    use crate::model::routing::{RoutingConfig, RoutingStrategy, StaticRoute};

    fn sample_config() -> NetworkConfiguration {
        NetworkConfiguration {
            version: "1.0".to_string(),
            backend: "hardy".to_string(),
            local_node: NodeDefinition {
                node_number: 10,
                endpoint_id: Some(EndpointId::Ipn {
                    node_number: 10,
                    service_number: 0,
                }),
                callsign_eid: Some(EndpointId::Dtn {
                    authority: "g4dpz-1".to_string(),
                    path: "gs".to_string(),
                }),
                name: "G4DPZ Ground Station".to_string(),
                services: vec![
                    ServiceDemux {
                        service_number: 1,
                        description: Some("Bundle delivery".to_string()),
                    },
                    ServiceDemux {
                        service_number: 7,
                        description: Some("Echo".to_string()),
                    },
                ],
            },
            neighbors: vec![Neighbor {
                node_number: 20,
                name: Some("Lunar Orbiter".to_string()),
                links: vec![ConvergenceLayerLink::LtpUdp {
                    id: "ltp-to-orbiter".to_string(),
                    local_engine_id: 10,
                    remote_engine_id: 20,
                    remote_host: "192.168.1.20".to_string(),
                    remote_port: 1113,
                    local_port: 2113,
                    mtu: Some(1360),
                    segment_rate: None,
                }],
                rate_limit_bps: None,
            }],
            contact_plan: ContactPlan {
                contacts: vec![
                    Contact {
                        source_node: 10,
                        dest_node: 20,
                        start_time: 1700000000,
                        end_time: 1700003600,
                        rate_bps: 9600,
                        confidence: 0.95,
                    },
                ],
                ranges: vec![Range {
                    source_node: 10,
                    dest_node: 20,
                    owlt_secs: 1.3,
                }],
            },
            routing: RoutingConfig {
                strategy: RoutingStrategy::Cgr,
                static_routes: vec![],
            },
            security: Some(SecurityConfig { enabled: false }),
            storage: Some(StorageConfig {
                path: "/var/radiant/bundles".to_string(),
                max_bytes: Some(1073741824),
            }),
            backend_options: HashMap::new(),
        }
    }

    #[test]
    fn test_generate_hardy_config_produces_yaml_file() {
        let config = sample_config();
        let generated = generate_hardy_config(&config);
        assert!(generated.files.contains_key("hardy.yaml"));
    }

    #[test]
    fn test_generates_static_routes_file_when_static_routing() {
        let mut config = sample_config();
        config.routing = RoutingConfig {
            strategy: RoutingStrategy::Static,
            static_routes: vec![StaticRoute {
                destination_node: 20,
                next_hop_node: 15,
            }],
        };
        let generated = generate_hardy_config(&config);
        assert!(generated.files.contains_key("hardy.yaml"));
        assert!(generated.files.contains_key("static_routes.yaml"));
        assert!(generated.files.contains_key("ltp-cla.yaml"));
        assert_eq!(generated.files.len(), 3);
    }

    #[test]
    fn test_no_static_routes_file_when_cgr_routing() {
        let config = sample_config();
        let generated = generate_hardy_config(&config);
        assert!(!generated.files.contains_key("static_routes.yaml"));
        // hardy.yaml + ltp-cla.yaml (sample_config has an LTP/UDP link)
        assert_eq!(generated.files.len(), 2);
    }

    #[test]
    fn test_node_ids_contains_both_ipn_and_dtn() {
        let config = sample_config();
        let yaml = generate_hardy_yaml(&config);
        assert!(yaml.contains("node-ids:"));
        assert!(yaml.contains("\"ipn:10.0\""));
        assert!(yaml.contains("\"dtn://g4dpz-1/gs\""));
    }

    #[test]
    fn test_node_ids_fallback_dtn_when_no_callsign() {
        let mut config = sample_config();
        config.local_node.callsign_eid = None;
        let yaml = generate_hardy_yaml(&config);
        assert!(yaml.contains("\"ipn:10.0\""));
        assert!(yaml.contains("\"dtn://node10/\""));
    }

    #[test]
    fn test_grpc_section_default() {
        let config = sample_config();
        let yaml = generate_hardy_yaml(&config);
        assert!(yaml.contains("grpc:"));
        assert!(yaml.contains("address: \"[::1]:50051\""));
        assert!(yaml.contains("services: [\"application\", \"cla\", \"service\", \"ltp\"]"));
    }

    #[test]
    fn test_grpc_section_custom_address() {
        let mut config = sample_config();
        config.backend_options.insert(
            "grpc_address".to_string(),
            serde_yaml::Value::String("0.0.0.0:9090".to_string()),
        );
        let yaml = generate_hardy_yaml(&config);
        assert!(yaml.contains("address: \"0.0.0.0:9090\""));
    }

    #[test]
    fn test_storage_section_with_persistent_storage() {
        let config = sample_config();
        let yaml = generate_hardy_yaml(&config);
        assert!(yaml.contains("storage:"));
        assert!(yaml.contains("type: \"sqlite\""));
        assert!(yaml.contains("path: \"/var/radiant/bundles/metadata.db\""));
        assert!(yaml.contains("type: \"localdisk\""));
        assert!(yaml.contains("path: \"/var/radiant/bundles/bundles\""));
    }

    #[test]
    fn test_storage_section_memory_when_no_storage_config() {
        let mut config = sample_config();
        config.storage = None;
        let yaml = generate_hardy_yaml(&config);
        assert!(yaml.contains("storage:"));
        // Both metadata and bundle should be memory
        let memory_count = yaml.matches("type: \"memory\"").count();
        assert_eq!(memory_count, 2);
    }

    #[test]
    fn test_rfc9171_validity_section() {
        let config = sample_config();
        let yaml = generate_hardy_yaml(&config);
        assert!(yaml.contains("rfc9171-validity:"));
        assert!(yaml.contains("primary-block-integrity: false"));
        assert!(yaml.contains("bundle-age-required: false"));
    }

    #[test]
    fn test_built_in_services_echo() {
        let config = sample_config();
        let yaml = generate_hardy_yaml(&config);
        assert!(yaml.contains("built-in-services:"));
        assert!(yaml.contains("echo: [7, \"echo\"]"));
    }

    #[test]
    fn test_built_in_services_additional() {
        let mut config = sample_config();
        config.local_node.services = vec![
            ServiceDemux {
                service_number: 7,
                description: Some("Echo".to_string()),
            },
            ServiceDemux {
                service_number: 99,
                description: Some("Telemetry".to_string()),
            },
        ];
        let yaml = generate_hardy_yaml(&config);
        assert!(yaml.contains("echo: [7, \"echo\"]"));
        assert!(yaml.contains("telemetry: [99, \"Telemetry\"]"));
    }

    #[test]
    fn test_static_routes_section_present_when_static() {
        let mut config = sample_config();
        config.routing = RoutingConfig {
            strategy: RoutingStrategy::Static,
            static_routes: vec![StaticRoute {
                destination_node: 20,
                next_hop_node: 15,
            }],
        };
        let yaml = generate_hardy_yaml(&config);
        assert!(yaml.contains("static-routes:"));
        assert!(yaml.contains("routes-file: \"static_routes.yaml\""));
    }

    #[test]
    fn test_static_routes_section_absent_when_cgr() {
        let config = sample_config();
        let yaml = generate_hardy_yaml(&config);
        assert!(!yaml.contains("static-routes:"));
    }

    #[test]
    fn test_clas_section_with_tcpcl_neighbor() {
        let mut config = sample_config();
        config.neighbors = vec![Neighbor {
            node_number: 40,
            name: Some("TCP Peer".to_string()),
            links: vec![ConvergenceLayerLink::TcpCl {
                id: "tcp-link-1".to_string(),
                remote_host: "10.0.0.40".to_string(),
                remote_port: 4556,
                local_port: Some(4557),
                keepalive_interval_secs: Some(30),
            }],
            rate_limit_bps: None,
        }];
        let yaml = generate_hardy_yaml(&config);
        assert!(yaml.contains("clas:"));
        assert!(yaml.contains("name: \"tcp-link-1\""));
        assert!(yaml.contains("type: \"tcpclv4\""));
        assert!(yaml.contains("address: \"[::]:4557\""));
        assert!(yaml.contains("segment-mru: 16384"));
        assert!(yaml.contains("transfer-mru: 562949953421312"));
    }

    #[test]
    fn test_clas_section_tcpcl_default_port() {
        let mut config = sample_config();
        config.neighbors = vec![Neighbor {
            node_number: 40,
            name: Some("TCP Peer".to_string()),
            links: vec![ConvergenceLayerLink::TcpCl {
                id: "tcp-default".to_string(),
                remote_host: "10.0.0.40".to_string(),
                remote_port: 4556,
                local_port: None,
                keepalive_interval_secs: None,
            }],
            rate_limit_bps: None,
        }];
        let yaml = generate_hardy_yaml(&config);
        assert!(yaml.contains("address: \"[::]:4556\""));
    }

    #[test]
    fn test_ltp_neighbor_noted_in_comments() {
        let config = sample_config();
        let yaml = generate_hardy_yaml(&config);
        // LTP link should appear as a comment, not a CLA entry
        assert!(yaml.contains("# NOTE: LTP/UDP/KISS convergence layers"));
        assert!(yaml.contains("hardy-ltp-cla"));
        assert!(yaml.contains("# - LTP/UDP link \"ltp-to-orbiter\" -> 192.168.1.20:1113"));
    }

    #[test]
    fn test_kiss_neighbor_noted_in_comments() {
        let mut config = sample_config();
        config.neighbors = vec![Neighbor {
            node_number: 30,
            name: Some("KISS TNC Peer".to_string()),
            links: vec![ConvergenceLayerLink::Kiss {
                id: "kiss-tnc".to_string(),
                tnc_device: "/dev/ttyUSB0".to_string(),
                baud_rate: 9600,
                local_engine_id: 10,
                remote_engine_id: 30,
                frame_size: Some(256),
            }],
            rate_limit_bps: None,
        }];
        let yaml = generate_hardy_yaml(&config);
        assert!(yaml.contains("# - KISS link \"kiss-tnc\" via /dev/ttyUSB0"));
    }

    #[test]
    fn test_no_contacts_or_ranges_in_config() {
        let config = sample_config();
        let yaml = generate_hardy_yaml(&config);
        // Hardy manages contacts via gRPC, NOT in config.yaml
        assert!(!yaml.contains("contacts:"));
        assert!(!yaml.contains("ranges:"));
    }

    #[test]
    fn test_no_bpsec_directives() {
        let config = sample_config();
        let yaml = generate_hardy_yaml(&config);
        // Filter out comment lines, then check no security directives remain
        let non_comment: String = yaml
            .lines()
            .filter(|l| !l.trim_start().starts_with('#'))
            .collect::<Vec<&str>>()
            .join("\n")
            .to_lowercase();
        assert!(!non_comment.contains("bpsec"));
        assert!(!non_comment.contains("encrypt"));
        assert!(!non_comment.contains("hmac"));
        assert!(!non_comment.contains("bcb"));
        assert!(!non_comment.contains("bib"));
    }

    #[test]
    fn test_log_level_default() {
        let config = sample_config();
        let yaml = generate_hardy_yaml(&config);
        assert!(yaml.contains("log-level: info"));
    }

    #[test]
    fn test_log_level_custom() {
        let mut config = sample_config();
        config.backend_options.insert(
            "log_level".to_string(),
            serde_yaml::Value::String("debug".to_string()),
        );
        let yaml = generate_hardy_yaml(&config);
        assert!(yaml.contains("log-level: debug"));
    }

    #[test]
    fn test_static_routes_yaml_content() {
        let mut config = sample_config();
        config.routing = RoutingConfig {
            strategy: RoutingStrategy::Static,
            static_routes: vec![
                StaticRoute {
                    destination_node: 20,
                    next_hop_node: 15,
                },
                StaticRoute {
                    destination_node: 30,
                    next_hop_node: 20,
                },
            ],
        };
        let routes = generate_static_routes_yaml(&config);
        assert!(routes.contains("routes:"));
        assert!(routes.contains("destination: \"ipn:20.0\""));
        assert!(routes.contains("next-hop: \"ipn:15.0\""));
        assert!(routes.contains("destination: \"ipn:30.0\""));
        assert!(routes.contains("next-hop: \"ipn:20.0\""));
    }

    #[test]
    fn test_mixed_tcpcl_and_ltp_neighbors() {
        let mut config = sample_config();
        config.neighbors = vec![
            Neighbor {
                node_number: 20,
                name: Some("LTP Peer".to_string()),
                links: vec![ConvergenceLayerLink::LtpUdp {
                    id: "ltp-link".to_string(),
                    local_engine_id: 10,
                    remote_engine_id: 20,
                    remote_host: "192.168.1.20".to_string(),
                    remote_port: 1113,
                    local_port: 2113,
                    mtu: None,
                    segment_rate: None,
                }],
                rate_limit_bps: None,
            },
            Neighbor {
                node_number: 30,
                name: Some("TCP Peer".to_string()),
                links: vec![ConvergenceLayerLink::TcpCl {
                    id: "tcp-link".to_string(),
                    remote_host: "192.168.1.30".to_string(),
                    remote_port: 4556,
                    local_port: Some(4560),
                    keepalive_interval_secs: None,
                }],
                rate_limit_bps: None,
            },
        ];
        let yaml = generate_hardy_yaml(&config);
        // TCPCL should appear in clas section
        assert!(yaml.contains("clas:"));
        assert!(yaml.contains("name: \"tcp-link\""));
        assert!(yaml.contains("type: \"tcpclv4\""));
        // LTP should appear in comments
        assert!(yaml.contains("# - LTP/UDP link \"ltp-link\""));
    }

    #[test]
    fn test_empty_neighbors_omits_clas() {
        let mut config = sample_config();
        config.neighbors = vec![];
        let yaml = generate_hardy_yaml(&config);
        assert!(!yaml.contains("clas:"));
    }

    #[test]
    fn test_output_is_valid_yaml() {
        let config = sample_config();
        let yaml = generate_hardy_yaml(&config);
        // Parse with serde_yaml to verify it's valid YAML
        let parsed: serde_yaml::Value = serde_yaml::from_str(&yaml).unwrap();
        assert!(parsed.is_mapping());
    }

    #[test]
    fn test_output_has_expected_top_level_keys() {
        let config = sample_config();
        let yaml = generate_hardy_yaml(&config);
        let parsed: serde_yaml::Value = serde_yaml::from_str(&yaml).unwrap();
        let map = parsed.as_mapping().unwrap();

        // Check required top-level keys exist
        assert!(map.contains_key(&serde_yaml::Value::String("log-level".to_string())));
        assert!(map.contains_key(&serde_yaml::Value::String("node-ids".to_string())));
        assert!(map.contains_key(&serde_yaml::Value::String("grpc".to_string())));
        assert!(map.contains_key(&serde_yaml::Value::String("storage".to_string())));
        assert!(map.contains_key(&serde_yaml::Value::String(
            "rfc9171-validity".to_string()
        )));
        assert!(map.contains_key(&serde_yaml::Value::String(
            "built-in-services".to_string()
        )));
    }

    #[test]
    fn test_node_ids_is_list_of_two() {
        let config = sample_config();
        let yaml = generate_hardy_yaml(&config);
        let parsed: serde_yaml::Value = serde_yaml::from_str(&yaml).unwrap();
        let node_ids = parsed["node-ids"].as_sequence().unwrap();
        assert_eq!(node_ids.len(), 2);
        // First should be ipn:, second should be dtn://
        let first = node_ids[0].as_str().unwrap();
        let second = node_ids[1].as_str().unwrap();
        assert!(first.starts_with("ipn:"));
        assert!(second.starts_with("dtn://"));
    }

    #[test]
    fn test_ltp_cla_yaml_generated_for_ltp_links() {
        let config = sample_config();
        let generated = generate_hardy_config(&config);
        assert!(generated.files.contains_key("ltp-cla.yaml"));
        let ltp_yaml = &generated.files["ltp-cla.yaml"];

        // Verify structure matches hardy-ltp-server ServerConfig expectations
        assert!(ltp_yaml.contains("grpc:"), "should have grpc section");
        assert!(ltp_yaml.contains("endpoint:"), "should have grpc endpoint");
        assert!(ltp_yaml.contains("ltp:"), "should have ltp section");
        assert!(
            ltp_yaml.contains("engine-id: 10"),
            "should set local engine-id from link's local_engine_id"
        );
        assert!(
            ltp_yaml.contains("bind: \"0.0.0.0:2113\""),
            "should bind to the link's local_port"
        );
        assert!(
            ltp_yaml.contains("client-service-id: 1"),
            "should have client-service-id"
        );

        // Verify span for the remote engine
        assert!(ltp_yaml.contains("spans:"), "should have spans section");
        assert!(
            ltp_yaml.contains("engine-id: 20"),
            "span should reference remote engine-id"
        );
        assert!(
            ltp_yaml.contains("192.168.1.20:1113"),
            "span should have remote address:port"
        );
        assert!(
            ltp_yaml.contains("max-segment-size: 1360"),
            "span should use configured MTU"
        );
        assert!(
            ltp_yaml.contains("framing: none"),
            "span should use raw framing for interop"
        );
        assert!(
            ltp_yaml.contains("\"ipn:20.0\""),
            "span should include remote node-id"
        );
    }

    #[test]
    fn test_ltp_cla_yaml_not_generated_without_ltp_links() {
        let mut config = sample_config();
        // Replace LTP neighbor with a TCP neighbor
        config.neighbors = vec![Neighbor {
            node_number: 30,
            name: Some("TCP Peer".to_string()),
            links: vec![ConvergenceLayerLink::TcpCl {
                id: "tcp-only".to_string(),
                remote_host: "10.0.0.30".to_string(),
                remote_port: 4556,
                local_port: None,
                keepalive_interval_secs: None,
            }],
            rate_limit_bps: None,
        }];
        let generated = generate_hardy_config(&config);
        assert!(
            !generated.files.contains_key("ltp-cla.yaml"),
            "ltp-cla.yaml should NOT be generated without LTP/UDP links"
        );
    }

    #[test]
    fn test_ltp_cla_yaml_is_valid_yaml() {
        let config = sample_config();
        let generated = generate_hardy_config(&config);
        let ltp_yaml = &generated.files["ltp-cla.yaml"];
        let parsed: serde_yaml::Value =
            serde_yaml::from_str(ltp_yaml).expect("ltp-cla.yaml should be valid YAML");
        assert!(parsed.is_mapping());

        // Verify top-level keys
        let map = parsed.as_mapping().unwrap();
        assert!(map.contains_key(&serde_yaml::Value::String("grpc".to_string())));
        assert!(map.contains_key(&serde_yaml::Value::String("ltp".to_string())));
    }
}
